name: Create Ceneton SQLite Database

on:
  workflow_dispatch:
    inputs:
      output_filename:
        description: 'Name of the output file to create'
        required: true
        default: 'ceneton.db'
        type: string

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Clone ceneton-database-tools
      id: clone-tools
      run: |
        git clone https://github.com/kws/ceneton-database-tools.git
        cd ceneton-database-tools
        echo "commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "Using ceneton-database-tools commit: $(git rev-parse HEAD)"
        pip install .        
    - name: Log commit information
      run: |
        echo "Ceneton Database Tools commit SHA: ${{ steps.clone-tools.outputs.commit-sha }}"
    - name: Run Python task
      run: |
        ct-db create-db \
           "archive" \
           "sqlite:///${{ github.event.inputs.output_filename }}" \
           --table-name ceneton \
           --db-metadata "tools-commit-sha=${{ steps.clone-tools.outputs.commit-sha }}" \
           --db-metadata "database-commit-sha=$(git rev-parse HEAD)"
                      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ceneton-sqlite-database
        path: ${{ github.event.inputs.output_filename }}
        retention-days: 90
      if: success() && hashFiles(github.event.inputs.output_filename) != ''