name: Publish Ceneton SQLite Database on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  create-and-attach:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Clone ceneton-database-tools
      id: clone-tools
      run: |
        git clone https://github.com/kws/ceneton-database-tools.git
        cd ceneton-database-tools
        echo "commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "Using ceneton-database-tools commit: $(git rev-parse HEAD)"
        pip install .
        
    - name: Log commit information
      run: |
        echo "Ceneton Database Tools commit SHA: ${{ steps.clone-tools.outputs.commit-sha }}"
        
    - name: Generate release filename
      id: filename
      run: |
        # DATE=$(date '+%Y-%m-%d')
        # FILENAME="ceneton-release-${DATE}-${{ github.event.release.tag_name }}.db"
        FILENAME="ceneton.db"
        echo "filename=${FILENAME}" >> $GITHUB_OUTPUT
        
    - name: Run Python task for release
      run: |
        ct-db create-db \
          "archive" \
          "sqlite:///${{ steps.filename.outputs.filename }}" \
          --table-name ceneton \
          --db-metadata "tools-commit-sha=${{ steps.clone-tools.outputs.commit-sha }}" \
          --db-metadata "database-commit-sha=$(git rev-parse HEAD)" \
          --db-metadata "release-tag=${{ github.event.release.tag_name }}"
          
    - name: Attach file to release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.filename.outputs.filename }}
        tag_name: ${{ github.event.release.tag_name }}
      if: success()
        
    - name: Also upload as workflow artifact (backup)
      uses: actions/upload-artifact@v4
      with:
        name: release-processed-files
        path: ${{ steps.filename.outputs.filename }}
        retention-days: 7
      if: success() && hashFiles(steps.filename.outputs.filename) != '' 