name: Publish Ceneton SQLite Database on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  create-and-attach:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/kws/ceneton-database-tools
        
    - name: Generate release filename
      id: filename
      run: |
        # DATE=$(date '+%Y-%m-%d')
        # FILENAME="ceneton-release-${DATE}-${{ github.event.release.tag_name }}.db"
        FILENAME="ceneton.db"
        echo "filename=${FILENAME}" >> $GITHUB_OUTPUT
        
    - name: Run Python task for release
      run: |
        ct-db create-db \
          "archive/2025-02-17T13-30-06.xml.bz2" \
          "sqlite:///${{ steps.filename.outputs.filename }}"
          
    - name: Attach file to release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.filename.outputs.filename }}
        tag_name: ${{ github.event.release.tag_name }}
      if: success()
        
    - name: Also upload as workflow artifact (backup)
      uses: actions/upload-artifact@v4
      with:
        name: release-processed-files
        path: ${{ steps.filename.outputs.filename }}
        retention-days: 7
      if: success() && hashFiles(steps.filename.outputs.filename) != '' 